# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class ClaimResponseProcessNoteType(str, enum.Enum):
    """
    The business purpose of the note text.
    """

    DISPLAY = "display"
    PRINT = "print"
    PRINTOPER = "printoper"

    def visit(
        self,
        display: typing.Callable[[], T_Result],
        print: typing.Callable[[], T_Result],
        printoper: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is ClaimResponseProcessNoteType.DISPLAY:
            return display()
        if self is ClaimResponseProcessNoteType.PRINT:
            return print()
        if self is ClaimResponseProcessNoteType.PRINTOPER:
            return printoper()
