# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class MolecularSequenceRepositoryType(str, enum.Enum):
    """
    Click and see / RESTful API / Need login to see / RESTful API with authentication / Other ways to see resource.
    """

    DIRECTLINK = "directlink"
    OPENAPI = "openapi"
    LOGIN = "login"
    OAUTH = "oauth"
    OTHER = "other"

    def visit(
        self,
        directlink: typing.Callable[[], T_Result],
        openapi: typing.Callable[[], T_Result],
        login: typing.Callable[[], T_Result],
        oauth: typing.Callable[[], T_Result],
        other: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is MolecularSequenceRepositoryType.DIRECTLINK:
            return directlink()
        if self is MolecularSequenceRepositoryType.OPENAPI:
            return openapi()
        if self is MolecularSequenceRepositoryType.LOGIN:
            return login()
        if self is MolecularSequenceRepositoryType.OAUTH:
            return oauth()
        if self is MolecularSequenceRepositoryType.OTHER:
            return other()
