# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class PasswordChangeRequestType(str, enum.Enum):
    """
    The type of password change request (invite or reset).
    """

    INVITE = "invite"
    RESET = "reset"

    def visit(self, invite: typing.Callable[[], T_Result], reset: typing.Callable[[], T_Result]) -> T_Result:
        if self is PasswordChangeRequestType.INVITE:
            return invite()
        if self is PasswordChangeRequestType.RESET:
            return reset()
