# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class ResearchElementDefinitionVariableType(str, enum.Enum):
    """
    The type of the outcome (e.g. Dichotomous, Continuous, or Descriptive).
    """

    DICHOTOMOUS = "dichotomous"
    CONTINUOUS = "continuous"
    DESCRIPTIVE = "descriptive"

    def visit(
        self,
        dichotomous: typing.Callable[[], T_Result],
        continuous: typing.Callable[[], T_Result],
        descriptive: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is ResearchElementDefinitionVariableType.DICHOTOMOUS:
            return dichotomous()
        if self is ResearchElementDefinitionVariableType.CONTINUOUS:
            return continuous()
        if self is ResearchElementDefinitionVariableType.DESCRIPTIVE:
            return descriptive()
