# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class TestScriptAssertResponse(str, enum.Enum):
    """
    okay | created | noContent | notModified | bad | forbidden | notFound | methodNotAllowed | conflict | gone | preconditionFailed | unprocessable.
    """

    OKAY = "okay"
    CREATED = "created"
    NO_CONTENT = "noContent"
    NOT_MODIFIED = "notModified"
    BAD = "bad"
    FORBIDDEN = "forbidden"
    NOT_FOUND = "notFound"
    METHOD_NOT_ALLOWED = "methodNotAllowed"
    CONFLICT = "conflict"
    GONE = "gone"
    PRECONDITION_FAILED = "preconditionFailed"
    UNPROCESSABLE = "unprocessable"

    def visit(
        self,
        okay: typing.Callable[[], T_Result],
        created: typing.Callable[[], T_Result],
        no_content: typing.Callable[[], T_Result],
        not_modified: typing.Callable[[], T_Result],
        bad: typing.Callable[[], T_Result],
        forbidden: typing.Callable[[], T_Result],
        not_found: typing.Callable[[], T_Result],
        method_not_allowed: typing.Callable[[], T_Result],
        conflict: typing.Callable[[], T_Result],
        gone: typing.Callable[[], T_Result],
        precondition_failed: typing.Callable[[], T_Result],
        unprocessable: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is TestScriptAssertResponse.OKAY:
            return okay()
        if self is TestScriptAssertResponse.CREATED:
            return created()
        if self is TestScriptAssertResponse.NO_CONTENT:
            return no_content()
        if self is TestScriptAssertResponse.NOT_MODIFIED:
            return not_modified()
        if self is TestScriptAssertResponse.BAD:
            return bad()
        if self is TestScriptAssertResponse.FORBIDDEN:
            return forbidden()
        if self is TestScriptAssertResponse.NOT_FOUND:
            return not_found()
        if self is TestScriptAssertResponse.METHOD_NOT_ALLOWED:
            return method_not_allowed()
        if self is TestScriptAssertResponse.CONFLICT:
            return conflict()
        if self is TestScriptAssertResponse.GONE:
            return gone()
        if self is TestScriptAssertResponse.PRECONDITION_FAILED:
            return precondition_failed()
        if self is TestScriptAssertResponse.UNPROCESSABLE:
            return unprocessable()
