# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class MapiWebhookStatus(str, enum.Enum):
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"

    def visit(
        self,
        processing: typing.Callable[[], T_Result],
        completed: typing.Callable[[], T_Result],
        failed: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is MapiWebhookStatus.PROCESSING:
            return processing()
        if self is MapiWebhookStatus.COMPLETED:
            return completed()
        if self is MapiWebhookStatus.FAILED:
            return failed()
