# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class CatalogEntryRelatedEntryRelationtype(str, enum.Enum):
    """
    The type of relation to the related item: child, parent, packageContent, containerPackage, usedIn, uses, requires, etc.
    """

    TRIGGERS = "triggers"
    IS_REPLACED_BY = "is-replaced-by"

    def visit(self, triggers: typing.Callable[[], T_Result], is_replaced_by: typing.Callable[[], T_Result]) -> T_Result:
        if self is CatalogEntryRelatedEntryRelationtype.TRIGGERS:
            return triggers()
        if self is CatalogEntryRelatedEntryRelationtype.IS_REPLACED_BY:
            return is_replaced_by()
