# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class PersonLinkAssurance(str, enum.Enum):
    """
    Level of assurance that this link is associated with the target resource.
    """

    LEVEL_1 = "level1"
    LEVEL_2 = "level2"
    LEVEL_3 = "level3"
    LEVEL_4 = "level4"

    def visit(
        self,
        level_1: typing.Callable[[], T_Result],
        level_2: typing.Callable[[], T_Result],
        level_3: typing.Callable[[], T_Result],
        level_4: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is PersonLinkAssurance.LEVEL_1:
            return level_1()
        if self is PersonLinkAssurance.LEVEL_2:
            return level_2()
        if self is PersonLinkAssurance.LEVEL_3:
            return level_3()
        if self is PersonLinkAssurance.LEVEL_4:
            return level_4()
