# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class PractitionerGender(str, enum.Enum):
    """
    Administrative Gender - the gender that the person is considered to have for administration and record keeping purposes.
    """

    MALE = "male"
    FEMALE = "female"
    OTHER = "other"
    UNKNOWN = "unknown"

    def visit(
        self,
        male: typing.Callable[[], T_Result],
        female: typing.Callable[[], T_Result],
        other: typing.Callable[[], T_Result],
        unknown: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is PractitionerGender.MALE:
            return male()
        if self is PractitionerGender.FEMALE:
            return female()
        if self is PractitionerGender.OTHER:
            return other()
        if self is PractitionerGender.UNKNOWN:
            return unknown()
