# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class TestScriptOperationMethod(str, enum.Enum):
    """
    The HTTP method the test engine MUST use for this operation regardless of any other operation details.
    """

    DELETE = "delete"
    GET = "get"
    OPTIONS = "options"
    PATCH = "patch"
    POST = "post"
    PUT = "put"
    HEAD = "head"

    def visit(
        self,
        delete: typing.Callable[[], T_Result],
        get: typing.Callable[[], T_Result],
        options: typing.Callable[[], T_Result],
        patch: typing.Callable[[], T_Result],
        post: typing.Callable[[], T_Result],
        put: typing.Callable[[], T_Result],
        head: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is TestScriptOperationMethod.DELETE:
            return delete()
        if self is TestScriptOperationMethod.GET:
            return get()
        if self is TestScriptOperationMethod.OPTIONS:
            return options()
        if self is TestScriptOperationMethod.PATCH:
            return patch()
        if self is TestScriptOperationMethod.POST:
            return post()
        if self is TestScriptOperationMethod.PUT:
            return put()
        if self is TestScriptOperationMethod.HEAD:
            return head()
