# This file was auto-generated by Fern from our API Definition.

from backports.cached_property import cached_property

from .environment import MercoaEnvironment
from .resources.document.client import AsyncDocumentClient, DocumentClient


class Mercoa:
    def __init__(self, *, environment: MercoaEnvironment = MercoaEnvironment.PRODUCTION, api_key: str):
        self._environment = environment
        self.api_key = api_key

    @cached_property
    def document(self) -> DocumentClient:
        return DocumentClient(environment=self._environment, api_key=self.api_key)


class AsyncMercoa:
    def __init__(self, *, environment: MercoaEnvironment = MercoaEnvironment.PRODUCTION, api_key: str):
        self._environment = environment
        self.api_key = api_key

    @cached_property
    def document(self) -> AsyncDocumentClient:
        return AsyncDocumentClient(environment=self._environment, api_key=self.api_key)
